name: Test_Rohit_Twelve_Thirty

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '30 6 * * *'

env:
  EMAIL_ADDRESS:  ${{ secrets.EMAIL_ADDRESS }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  KITE_URL: ${{ secrets.KITE_URL }}
  KITE_USERID: ${{ secrets.KITE_USERID }}
  KITE_PASSWORD: ${{ secrets.KITE_PASSWORD }}
  KITE_PIN: ${{ secrets.KITE_PIN }}
  KITE_APIKEY: ${{ secrets.KITE_APIKEY }}
  KITE_APISECRET: ${{ secrets.KITE_APISECRET }}
  TWELVE_THIRTY_LOT_QUANTITY: ${{ secrets.TWELVE_THIRTY_LOT_QUANTITY }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Github
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: |
        chromedriver --url-base=/wd/hub --port=8080 &
    - name: Run 12:30 pm Strategy
      run: go run main.go twelvethirty
